CREATE TABLE dbo.qsa_dados_cadastrais (
    linha bigint,
    cnpj varchar(14),
    identificador_matriz_filial int,
    razaoSocial_nome_empresarial varchar(150),
    nome_fantasia varchar(55),
    situacao_cadastral int,
    data_situacao_cadastral_ano int,
    data_situacao_cadastral_mes int,
    data_situacao_cadastral_dia int,
    motivo_situacao_cadastral int,
    nm_cidade varchar(55),
    co_pais varchar(3),
    nm_pais varchar(70),
    codigo_natureza_juridica int,
    data_inicio_atividade_ano int,
    data_inicio_atividade_mes int,
    data_inicio_atividade_dia int,
    cnae_fiscal int,
    descricao_tipo_logradouro varchar(20),
    logradouro varchar(60),
    numero varchar(6),
    complemento varchar(156),
    bairro varchar(50),
    cep int,
    uf varchar(2),
    codigo_municipio int,
    municipio varchar(50),
    ddd_1 varchar(4),
    telefone_1 varchar(8),
    ddd_2 varchar(4),
    telefone_2 varchar(8),
    nu_ddd_fax varchar(4),
    nu_fax varchar(8),
    correio_eletronico varchar(115),
    qualificacao_do_responsavel int,
    capital_social_da_empresa numeric(16,2),
    porte_empresa varchar(2),
    opcao_pelo_simples varchar(1),
    data_opcao_pelo_simples_ano int,
    data_opcao_pelo_simples_mes int,
    data_opcao_pelo_simples_dia int,
    data_exclusao_do_simples_ano int,
    data_exclusao_do_simples_mes int,
    data_exclusao_do_simples_dia int,
    opcao_pelo_mei varchar(1),
    situacao_especial varchar(23),
    data_situacao_especial_ano int,
    data_situacao_especial_mes int,
    data_situacao_especial_dia int
)

CREATE TABLE dbo.qsa_socios (
    linha bigint,
    cnpj varchar(14),
    identificador_de_socio varchar(1),
    nome_socio_razao_social varchar(150),
    cnpj_cpf_socio varchar(14),
    codigo_qualificacao_socio varchar(2),
    percentual_capital_social int,
    data_entrada_sociedade_ano int,
    data_entrada_sociedade_mes int,
    data_entrada_sociedade_dia int,
    codigo_pais varchar(3),
    nome_pais_socio varchar(70),
    cpf_representante_legal varchar(11),
    nome_representante varchar(60),
    codigo_qualificacao_representante_legal varchar(2),
)

CREATE TABLE  dbo.qsa_cnaes_secundarios (
    linha bigint,
    cnpj varchar(14),
    cnae_secundaria int
)